version: "3.7"

services:
  client:
    container_name: client
    build:
      context: docker
      dockerfile: nginx/Dockerfile
    volumes:
      - .:/app
    ports:
      - "${DOCKER_CLIENT_HTTP_PORT}:80"
      - "${DOCKER_CLIENT_HTTPS_PORT}:443"

  client-node:
    container_name: client.node
    build:
      context: .
      dockerfile: docker/node/dev.dockerfile
    volumes:
      - .:/app
    ports:
      - "${DOCKER_NODE_PORT}:8080"


volumes:
  composer:
  ssh_dir: {}